### ISSUE TITLE
Dll source code

### ISSUE THREAD

**Issue by SimoneNigro** [chinue/Fast-SSIM#2]
Hi, is your fast ssim implementation based on [this](https://ieeexplore.ieee.org/document/5495310) paper or it's something  you came up on your own? Is the source code available somewhere?

**Comment by skuda** [comment]
I'm interested in review the source for the DLL as well

**Comment by SimoneNigro** [comment]
Source uploaded in commit 9f67122dfef8e47340c4cf11fff0edc3df778899 . Thanks!
